import type { Client, Employee, VideoProject } from "./types"

export const mockClients: Client[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john@techcorp.com",
    phone: "+1 (555) 123-4567",
    company: "TechCorp Inc.",
    address: "123 Tech Street, Silicon Valley, CA 94000",
    projectDescription: "Need a professional video showcasing our new AI product line with modern animations and voice-over.",
    status: "active" as const,
    createdAt: new Date("2024-01-15"),
    stage: { id: 3, name: "MSA Creation", description: "Master Service Agreement preparation", completed: false },
    assignedEmployees: ["emp-1", "emp-3"],
    assets: [
      {
        id: "asset-1",
        name: "logo.png",
        type: "image/png",
        size: 245760,
        uploadedAt: new Date("2024-01-16"),
        url: "/generic-company-logo.png",
      },
      {
        id: "asset-2",
        name: "brand-guidelines.pdf",
        type: "application/pdf",
        size: 1048576,
        uploadedAt: new Date("2024-01-16"),
        url: "#",
      },
    ],
    msaCompleted: false,
    projectCompleted: false,
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah@designstudio.com",
    phone: "+1 (555) 987-6543",
    company: "Design Studio LLC",
    address: "456 Creative Ave, New York, NY 10001",
    projectDescription: "Create an engaging promotional video for our design services with creative transitions and upbeat music.",
    status: "active" as const,
    createdAt: new Date("2024-01-20"),
    stage: { id: 4, name: "Employee Assignment", description: "Assign project to team member", completed: true },
    assignedEmployees: ["emp-2"],
    assets: [
      {
        id: "asset-3",
        name: "mockups.zip",
        type: "application/zip",
        size: 5242880,
        uploadedAt: new Date("2024-01-21"),
        url: "#",
      },
    ],
    msaCompleted: true,
    projectCompleted: false,
  },
  {
    id: "3",
    name: "Michael Chen",
    email: "michael@startupco.com",
    phone: "+1 (555) 246-8135",
    company: "StartupCo",
    address: "789 Innovation Blvd, Austin, TX 78701",
    projectDescription: "Looking for a dynamic explainer video for our SaaS platform with animated graphics and professional narration.",
    status: "active" as const,
    createdAt: new Date("2024-01-25"),
    stage: { id: 1, name: "Client Creation", description: "Initial client setup and onboarding", completed: true },
    assignedEmployees: [],
    assets: [],
    msaCompleted: false,
    projectCompleted: false,
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "Alice Cooper",
    email: "alice@company.com",
    role: "Senior Designer",
    assignedClients: ["1"],
  },
  {
    id: "emp-2",
    name: "Bob Wilson",
    email: "bob@company.com",
    role: "Project Manager",
    assignedClients: ["2"],
  },
  {
    id: "emp-3",
    name: "Carol Davis",
    email: "carol@company.com",
    role: "Developer",
    assignedClients: [],
  },
]

export const mockVideoProjects: VideoProject[] = [
  {
    id: "video-1",
    clientId: "1",
    clientName: "John Smith",
    company: "TechCorp Inc.",
    employeeId: "emp-1",
    assignedAt: new Date("2024-01-18"),
    currentStage: {
      id: 2,
      name: "Script Generation",
      description: "Create AI-generated script based on client requirements",
      completed: false,
    },
    assets: [
      {
        id: "asset-1",
        name: "logo.png",
        type: "image/png",
        size: 245760,
        uploadedAt: new Date("2024-01-16"),
        url: "/generic-company-logo.png",
      },
      {
        id: "asset-2",
        name: "brand-guidelines.pdf",
        type: "application/pdf",
        size: 1048576,
        uploadedAt: new Date("2024-01-16"),
        url: "#",
      },
    ],
    generatedImages: [],
    script: "Welcome to TechCorp Inc., where innovation meets excellence...",
    voiceSettings: {
      voice: "professional-male",
      speed: 1.0,
      tone: "confident",
    },
    videoSettings: {
      duration: 60,
      style: "corporate",
      resolution: "1080p",
    },
    completed: false,
  },
  {
    id: "video-2",
    clientId: "2",
    clientName: "Sarah Johnson",
    company: "Design Studio LLC",
    employeeId: "emp-2",
    assignedAt: new Date("2024-01-22"),
    currentStage: {
      id: 4,
      name: "Motion Creation",
      description: "Apply motion and animation to generated assets",
      completed: false,
    },
    assets: [
      {
        id: "asset-3",
        name: "mockups.zip",
        type: "application/zip",
        size: 5242880,
        uploadedAt: new Date("2024-01-21"),
        url: "#",
      },
    ],
    generatedImages: [
      {
        id: "gen-img-1",
        name: "hero-background.jpg",
        type: "image/jpeg",
        size: 1024000,
        uploadedAt: new Date("2024-01-23"),
        url: "#",
      },
      {
        id: "gen-img-2",
        name: "product-showcase.png",
        type: "image/png",
        size: 2048000,
        uploadedAt: new Date("2024-01-23"),
        url: "#",
      },
    ],
    script: "Design Studio LLC - Crafting beautiful experiences that inspire and engage...",
    voiceSettings: {
      voice: "creative-female",
      speed: 0.9,
      tone: "inspiring",
    },
    videoSettings: {
      duration: 90,
      style: "creative",
      resolution: "4K",
    },
    completed: false,
  },
]
